# 构建阶段
FROM node:16 AS build-stage

WORKDIR /app

# 将 package.json 和 package-lock.json 复制到容器内
COPY package*.json ./

# 安装依赖
RUN npm install

# 将所有源代码复制到容器内
COPY . .

# 构建 Vue 应用
RUN npm run build

# 生产阶段
FROM nginx:1.21.5

# 复制构建好的 dist 文件到 Nginx 默认的静态文件目录
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 复制自定义的 nginx 配置文件
COPY nginx.conf /etc/nginx/nginx.conf

# 设置时区和语言环境
ENV LANG=zh_CN.UTF-8 \
    LC_ALL=zh_CN.UTF-8 \
    TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 启动 Nginx 服务
CMD ["nginx", "-g", "daemon off;"]

# 暴露端口
EXPOSE 9099
