const dateMockData= {
  "data":{ "default": {
            "month": "4",
            "stage": "",
            "year": "2024",
            "quarter": "0"
        },
      "list":[
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 4,
                "monthno": 4,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 3,
                "monthno": 3,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "05",
                "stagenopre": "01",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "01-05",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "9",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-9",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "8",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-8",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "6",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-6",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "5",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-5",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "4",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-4",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2024,
                "publiclytime": "",
                "stagenosuf": "3",
                "stagenopre": "2",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "2-3",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 12,
                "monthno": 12,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 11,
                "monthno": 11,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 8,
                "monthno": 8,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 7,
                "monthno": 7,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 6,
                "monthno": 6,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 5,
                "monthno": 5,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 4,
                "monthno": 4,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 3,
                "monthno": 3,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 2,
                "monthno": 2,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 1,
                "monthno": 1,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 4,
                "isskip": "0",
                "quarter": 4
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 3,
                "isskip": "0",
                "quarter": 3
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 2,
                "isskip": "0",
                "quarter": 2
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 1,
                "isskip": "0",
                "quarter": 1
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "5",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-5",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "12",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-12",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2023,
                "publiclytime": "",
                "stagenosuf": "9",
                "stagenopre": "2",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "2-9",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 12,
                "monthno": 12,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 11,
                "monthno": 11,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 10,
                "monthno": 10,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 9,
                "monthno": 9,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 8,
                "monthno": 8,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 7,
                "monthno": 7,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 6,
                "monthno": 6,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 5,
                "monthno": 5,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 4,
                "monthno": 4,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 3,
                "monthno": 3,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 2,
                "monthno": 2,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 1,
                "monthno": 1,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 4,
                "isskip": "0",
                "quarter": 4
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 3,
                "isskip": "0",
                "quarter": 3
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 2,
                "isskip": "0",
                "quarter": 2
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 1,
                "isskip": "0",
                "quarter": 1
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "9",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-9",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "8",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-8",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "7",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-7",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "6",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-6",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "5",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-5",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "4",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-4",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "3",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-3",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "2",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-2",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "12",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-12",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "11",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-11",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "10",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-10",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2022,
                "publiclytime": "",
                "stagenosuf": "1",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-1",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 12,
                "monthno": 12,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 11,
                "monthno": 11,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 10,
                "monthno": 10,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 9,
                "monthno": 9,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 8,
                "monthno": 8,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 7,
                "monthno": 7,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 6,
                "monthno": 6,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 5,
                "monthno": 5,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 4,
                "monthno": 4,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 3,
                "monthno": 3,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 2,
                "monthno": 2,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 1,
                "monthno": 1,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 4,
                "isskip": "0",
                "quarter": 4
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 3,
                "isskip": "0",
                "quarter": 3
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 2,
                "isskip": "0",
                "quarter": 2
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 1,
                "isskip": "0",
                "quarter": 1
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "9",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-9",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "8",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-8",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "7",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-7",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "6",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-6",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "5",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-5",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "4",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-4",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "3",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-3",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "2",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-2",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "12",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-12",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "11",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-11",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "10",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-10",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2021,
                "publiclytime": "",
                "stagenosuf": "11",
                "stagenopre": "6",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "6-11",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 12,
                "monthno": 12,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 11,
                "monthno": 11,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 10,
                "monthno": 10,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 9,
                "monthno": 9,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 8,
                "monthno": 8,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 7,
                "monthno": 7,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 6,
                "monthno": 6,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 5,
                "monthno": 5,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 4,
                "monthno": 4,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 3,
                "monthno": 3,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 2,
                "monthno": 2,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 1,
                "monthno": 1,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 4,
                "isskip": "0",
                "quarter": 4
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 3,
                "isskip": "0",
                "quarter": 3
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 2,
                "isskip": "0",
                "quarter": 2
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 1,
                "isskip": "0",
                "quarter": 1
            },
            {
                "year": 2020,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 12,
                "monthno": 12,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 11,
                "monthno": 11,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 10,
                "monthno": 10,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 9,
                "monthno": 9,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 8,
                "monthno": 8,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 7,
                "monthno": 7,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 6,
                "monthno": 6,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 5,
                "monthno": 5,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 4,
                "monthno": 4,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 3,
                "monthno": 3,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 1,
                "monthno": 1,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 4,
                "isskip": "0",
                "quarter": 4
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 3,
                "isskip": "0",
                "quarter": 3
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 2,
                "isskip": "0",
                "quarter": 2
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 1,
                "isskip": "0",
                "quarter": 1
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "9",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-9",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "8",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-8",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "7",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-7",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "6",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-6",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "5",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-5",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "4",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-4",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "3",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-3",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "2",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-2",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "12",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-12",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "11",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-11",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2019,
                "publiclytime": "",
                "stagenosuf": "10",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-10",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2018,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 10,
                "monthno": 10,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2018,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 8,
                "monthno": 8,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 12,
                "monthno": 12,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 11,
                "monthno": 11,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 10,
                "monthno": 10,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 9,
                "monthno": 9,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 8,
                "monthno": 8,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 7,
                "monthno": 7,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 6,
                "monthno": 6,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 5,
                "monthno": 5,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 4,
                "monthno": 4,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 3,
                "monthno": 3,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 2,
                "monthno": 2,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 1,
                "monthno": 1,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 4,
                "isskip": "0",
                "quarter": 4
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 3,
                "isskip": "0",
                "quarter": 3
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 2,
                "isskip": "0",
                "quarter": 2
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 1,
                "isskip": "0",
                "quarter": 1
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "",
                "stagenopre": "",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "9",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-9",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "8",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-8",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "7",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-7",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "6",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-6",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "5",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-5",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "4",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-4",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "3",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-3",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "2",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-2",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "12",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-12",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "11",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-11",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            },
            {
                "year": 2000,
                "publiclytime": "",
                "stagenosuf": "10",
                "stagenopre": "1",
                "type": "",
                "version": "",
                "ischeck": "1",
                "kpuid": "",
                "month": 0,
                "monthno": 0,
                "isauto": "1",
                "timeStage": "1-10",
                "quarterno": 0,
                "isskip": "0",
                "quarter": 0
            }
        ]

  }
}

 const getMetrcisDate = () => {
   const {data}=dateMockData;
   return{
         code: 200,
        message: 'success',
        data: data
   }
}

export default {
 getMetrcisDate
}
